<?xml version="1.0" encoding="UTF-8"?>
<!--
Nombre: Ibrahim
Curso: DAW1
Fecha: 04/03/2025
Ejercicio: Ejercicio1-6 - Escritores
-->
<!-- Declaracion DTD -->
<!DOCTYPE escritores [
	<!ELEMENT escritores (escritor*)>
	<!ELEMENT escritor (nombre, nacimiento)>
	<!ELEMENT nombre (#PCDATA)>
	<!ELEMENT nacimiento (#PCDATA)>
]>
<!-- Contenedor de escritores -->
<escritores>
	<!-- Escritor indiviual -->
	<escritor>
		<!-- Descripcion del escritor -->
		<nombre>Mario Vargas Llosa</nombre>
		<nacimiento>28 de marzo de 1936</nacimiento>
	</escritor>
	<escritor>
		<nombre>Milan Kundera</nombre>
		<nacimiento>1 de abril de 1929</nacimiento>
	</escritor>
</escritores>