<?xml version="1.0" encoding="UTF-8"?>
<!--
Nombre: Ibrahim
Curso: DAW1
Fecha: 31/03/2025
Ejercicio: Ejercicio 3
-->
<!-- Declaracion del DTD -->
<!DOCTYPE aeropuerto [
	<!ELEMENT aeropuerto (nombre-aeropuerto, fecha-panel, vuelo+)>
	<!ELEMENT nombre-aeropuerto (#PCDATA)>
	<!ELEMENT fecha-panel (#PCDATA)>
	<!ELEMENT vuelo (diario?, origen, destino, hora-salida, hora-llegada)>
	<!ATTLIST vuelo
		codigo ID #REQUIRED
		estado (C|E|R) "E">
	<!ELEMENT diario EMPTY>
	<!ELEMENT origen (#PCDATA)>
	<!ELEMENT destino (#PCDATA)>
	<!ELEMENT hora-salida (#PCDATA)>
	<!ELEMENT hora-llegada (#PCDATA)>
]>
<!-- Contenedor del aeropuerto -->
<aeropuerto>
	<!-- Descripcion del aeropuerto -->
	<nombre-aeropuerto>John F. Kennedy International Airport (JFK)</nombre-aeropuerto>
	<fecha-panel>20/12/2013</fecha-panel>
	<!-- Contenedor de vuelo -->
	<vuelo codigo="V22" estado="R">
		<!-- Descripcion del vuelo -->
		<diario/>
		<origen>New York</origen>
		<destino>Chicago</destino>
		<hora-salida>9:30</hora-salida>
		<hora-llegada>11:30</hora-llegada>
	</vuelo>
	<vuelo codigo="V23" estado="C">
		<origen>New York</origen>
		<destino>Miami</destino>
		<hora-salida>10:15</hora-salida>
		<hora-llegada>11:15</hora-llegada>
	</vuelo>
</aeropuerto>