<?xml version="1.0" encoding="UTF-8"?>
<!--
Nombre: Ibrahim
Curso: DAW1
Fecha: 31/03/2025
Ejercicio: Ejercicio 2 
-->
<!-- Declaracion DTD -->
<!DOCTYPE EquiposNBA [
<!ELEMENT EquiposNBA (equipo|nombre)+>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT equipo (titulos, posicion, quimeto)>
<!ATTLIST equipo
	conferencia CDATA #REQUIRED>
<!ELEMENT titulos (#PCDATA)>
<!ELEMENT posicion (#PCDATA)>
<!ELEMENT quimeto (#PCDATA)>
]>
<EquiposNBA>
	<!-- Equipo con información completa -->
	<equipo conferencia="Oeste">
		<!-- Descripcion del equipo -->
		<nombre>Los Angeles Lakers</nombre>
		<titulos>17</titulos>
		<posicion>7</posicion>
		<quimeto>LeBron James, Anthony Davis, Russell Westbrook</quimeto>
	</equipo>
	
	<!-- Equipo con información completa -->
	<equipo conferencia="Este">
		<nombre>Boston Celtics</nombre>
		<titulos>17</titulos>
		<posicion>1</posicion>
		<quimeto>Jayson Tatum, Jaylen Brown, Marcus Smart</quimeto>
	</equipo>
	
	<!-- Solo nombre del equipo -->
	<nombre>Golden State Warriors</nombre>

	<equipo conferencia="Oeste">
		<nombre>Phoenix Suns</nombre>
		<titulos>0</titulos>
		<posicion>3</posicion>
		<quimeto>Devin Booker, Chris Paul, Deandre Ayton</quimeto>
	</equipo>
</EquiposNBA>