<?xml version="1.0" encoding="UTF-8"?>
<!--
Nombre: Ibrahim
Curso: DAW1
Fecha: 04/03/2025
Ejercicio: Ejercicio 2-3 - Aeropuertos
-->
<!-- Declaracion DTD -->
<!DOCTYPE aeropuertos [
	<!ELEMENT aeropuertos (aeropuerto*)>
	<!ELEMENT aeropuerto (nombre, cerrado?)>
	<!ELEMENT nombre (#PCDATA)>
	<!ELEMENT cerrado EMPTY>
]>
<!-- Contenedor de aeropuertos -->
<aeropuertos>
	<!-- Aeropuerto individual -->
	<aeropuerto>
		<!-- Nombre del aeropuerto -->
		<nombre>Berlin Schönefeld (SFX)</nombre>
	</aeropuerto>
	<aeropuerto>
		<nombre>Berlin Tempelhof (THF)</nombre>
		<!-- Indica que el aeropuerto está cerrado -->
		<cerrado />
	</aeropuerto>
</aeropuertos>