<?xml version="1.0" encoding="UTF-8"?>
<!--
Nombre: Ibrahim
Curso: DAW1
Fecha: 31/03/2025
Ejercicio: Ejercicio 3
-->
<!DOCTYPE agenda [
	<!ELEMENT agenda (nombre, apellido+, telefono, fecha_nacimiento, lugar_nacimiento)>
	<!ELEMENT nombre (#PCDATA)>
	<!ELEMENT apellido (#PCDATA)>
	<!ELEMENT telefono (#PCDATA)>
	<!ELEMENT fecha_nacimiento (anio, mes, dia)>
	<!ELEMENT anio (#PCDATA)>
	<!ELEMENT mes (#PCDATA)>
	<!ELEMENT dia (#PCDATA)>
	<!ELEMENT lugar_nacimiento (pais)>
	<!ELEMENT pais (#PCDATA)>
]>
<!-- Contenedor agenda -->
<agenda>
	<!-- Descripcion del contacto -->
	<nombre>Antonio</nombre>
	<apellido>Sánchez</apellido>
	<apellido>Pérez</apellido>
	<telefono>666555444</telefono>
	<!-- Fecha de nacimiento -->
	<fecha_nacimiento>
		<anio>2000</anio>
		<mes>01</mes>
		<dia>20</dia>
	</fecha_nacimiento>
	<!-- Lugar de nacimiento -->
	<lugar_nacimiento>
		<pais>España</pais>
	</lugar_nacimiento>
</agenda>